<h1>Netsuite Customers</h1>
<div class="container">
    <?php echo $table; ?>
</div>
<?php
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array('route'=>'netsuite/default','options'=>array('controller'=>'index','action'=>'customers'))
);
?>
