<H1><img class="record-icon" src="<?php echo $this->basePath('/img/recordicons/generictransaction.svg'); ?>"/> Customer Refund Record: <?php echo $fields['tranid']; ?> <div class="status"><?php echo empty($fields['status'])?$fields['paymentmethod']:$fields['status']; ?></div></H1>
<div class="static-fields">
    <div class="field-container">
        <div class="field"><b>Customer:</b><div><a href="/netsuite/index/customer?id=<?php echo $fields['companyid']; ?>"><?php echo $fields['customer']; ?></a></div></div>
        <div class="field"><b>Account:</b><div><?php echo $fields['account'] ?></div></div>
        <div class="field"><b>A/R Account:</b><div><?php echo $fields['aracct'] ?></div></div>
        <div class="field"><b>Date:</b><div><?php echo $fields['trandate'] ?></div></div>
        <div class="field"><b>Refund Amount:</b><div><?php echo $fields['total'] ?></div></div>
        <div class="field"><b>Balance:</b><div><?php echo $fields['balance'] ?></div></div>
        <div class="field"><b>Posting Period:</b><div><?php echo $fields['postingperiod'] ?></div></div>
        <div class="field"><b>Memo:</b><div><?php echo $fields['memo'] ?></div></div>
        <hr class="clear">
        <div class="field"><b>Subsidiary:</b><div><?php echo $fields['subsidiary'] ?></div></div>
        <div class="field"><b>Department:</b><div><?php echo $fields['department'] ?></div></div>
        <div class="field"><b>Address:</b><div><?php echo $fields['address'] ?></div></div>
        <!-- hr class="clear">
        <div class="field"><b>Discount:</b><div><?php echo $fields['discountitem'] ?></div></div>
        <div class="field"><b>Discount Rate:</b><div><?php echo $fields['discountrate'] ?></div></div>
        <div class="field"><b>Coupon Code:</b><div><?php echo $fields['couponcode'] ?></div></div>
        <div class="field"><b>Promotion:</b><div><?php echo $fields['promocode'] ?></div></div -->
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<div class="tabs">
    <div class="tab-header">
        <h3 id="apply-fields" class="active">Apply</h3>
        <h3 id="payments-fields">Payments</h3>
        <h3 id="relatedrecords-fields">Related Records</h3>
        <h3 id="messages-fields">Messages</h3>
        <h3 id="notes-fields">User Notes</h3>
        <h3 id="dynamic-fields">All Fields</h3>
        <span class="clear"></span>
    </div>
    <div class="apply-fields tab-content visible">

        <div class="clear"></div>
    </div>
    <div class="payments-fields tab-content">
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Contribution</div>
        <div class="field field-header">Employee</div>
        <div class="clear"></div>
        <?php echo $payments_table_html; ?>
    </div>
    <div class="relatedrecords-fields tab-content">
        <div class="field field-header">Type</div>
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Document Number</div>
        <div class="field field-header">Date Created</div>
        <div class="field field-header">Status</div>
        <div class="field field-header">Memo</div>
        <div class="clear"></div>
        <?php echo $related_table_html; ?>
    </div>
    <div class="messages-fields tab-content">
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Date</div>
        <div class="field field-header">Author</div>
        <div class="field field-header subject">Subject</div>
        <div class="field field-header">Attachment</div>
        <div class="clear"></div>
        <?php echo $messages_table_html; ?>
    </div>
    <div class="notes-fields tab-content">
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Date</div>
        <div class="field field-header">Author</div>
        <div class="field field-header">Title</div>
        <div class="field field-header note">Note</div>
        <div class="field field-header">Direction</div>
        <div class="clear"></div>
        <?php echo $notes_table_html; ?>
    </div>
    <div class="dynamic-fields tab-content"><?php echo $dynamic_fields; ?></div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath('/js/NStabs.js'); ?>"></script>