<style>.container{width:100%;}</style>
<H1>Inventory Item Record: <?php echo $fields['displayname']; ?> (<?php echo $fields['itemid']; ?>)</H1>
<div class="tabs">
    <div class="tab-header">
        <h3 id="prices-fields" >Prices</h3>
        <h3 id="inventory-fields">Inventory</h3>
        <h3 id="purchase-fields">Purchases</h3>
        <h3 id="dynamic-fields" class="active">All Fields</h3>
        <span class="clear"></span>
    </div>
    <div class="prices-fields tab-content">
    	<div class="field field-header">Price Level</div>
        <div class="field field-header">Quantity 1</div>
        <div class="field field-header">Quantity X</div>
        <div class="field field-header">Quantity Y</div>
        <div class="field field-header">Quantity Z</div>
        <div class="field field-header">Quantity ?</div>
        <div class="clear"></div>
    	<?php echo $prices_table_html; ?>		
    </div>
    <div class="inventory-fields tab-content">
        <div class="field field-header">Bin</div>
        <div class="field field-header">Location</div>
        <div class="clear"></div>
    	<?php echo $inventory_table_html; ?>
    </div>
    <div class="purchase-fields tab-content">
        <div class="field field-header">Item</div>
        <div class="field small-field field-header">Location</div>
        <div class="field small-field field-header">Quantity</div>
        <div class="field small-field field-header">Qty Billed</div>
        <div class="field small-field field-header">Qty Receiv</div>
        <div class="field small-field field-header">Rate</div>
        <div class="field small-field field-header">Amount</div>
        <div class="field field-header">MPN</div>
        <div class="field small-field field-header">?</div>
        <div class="field small-field field-header">Date</div>
        <div class="clear"></div>
        <?php echo $purchase_table_html; ?>
    </div>
    <div class="dynamic-fields tab-content visible"><?php echo $dynamic_fields; ?></div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('/js/NStabs.js'); ?>"></script>