<style>.container{width:100%;}</style>
<H1><img class="record-icon" src="<?php echo $this->basePath('/img/purchaseorder.svg'); ?>"/> Purchase Order Record: <?php echo $fields['tranid']; ?> <div class="status"><?php echo $fields['status']; ?></div></H1>
<div class="static-fields">
    <div class="field-container">
        <div class="field"><b>Vendor:</b><div><a href="/netsuite/index/vendor?id=<?php echo $fields['companyid']; ?>"><?php echo $fields['entity']; ?></a></div></div>
        <div class="field"><b>Subsidiary:</b><div><?php echo $fields['subsidiary'] ?></div></div>
        <div class="field"><b>Date:</b><div><?php echo $fields['trandate'] ?></div></div>
        <div class="field"><b>Vendor RMA #:</b><div><?php echo $fields['custbody_vendor_rma_number'] ?></div></div>
        <div class="field"><b>Vendor #:</b><div><?php echo $fields['otherrefnum'] ?></div></div>
        <div class="field"><b>Cancel Date:</b><div><?php echo $fields['custbody21'] ?></div></div>
        <div class="field"><b>Due Date:</b><div><?php echo $fields['duedate'] ?></div></div>
        <div class="field"><b>Memo:</b><div><?php echo $fields['memo'] ?></div></div>
        <hr class="clear">
        <div class="field"><b>Employee:</b><div><?php echo $fields['employee'] ?></div></div>
        <div class="field"><b>E-Mail:</b><div><?php echo $fields['email'] ?></div></div>
        <div class="field"><b>Department:</b><div><?php echo $fields['department'] ?></div></div>
        <div class="clear"></div>
    </div>
    <div class="totals">
        <div class="summary">Summary</div>
        <table class="totals-table">
            <tr><td>TERMS</td><td><?php echo $fields['terms']; ?></td></tr>
            <tr><td>TOTAL</td><td><?php echo number_format($fields['total'],2); ?></td></tr>
        </table>
    </div>
    <div class="clear"></div>
</div>
<div class="tabs">
    <div class="tab-header">
        <h3 id="items-fields" class="active">Items</h3>
        <h3 id="shipping-fields">Shipping</h3>
        <h3 id="billing-fields">Billing</h3>
        <h3 id="relatedrecords-fields">Related Records</h3>
        <h3 id="messages-fields">Messages</h3>
        <h3 id="notes-fields">User Notes</h3>
        <h3 id="dynamic-fields">All Fields</h3>
        <span class="clear"></span>
    </div>
    <div class="items-fields tab-content visible">
        <div class="field field-header small-field">Internal ID</div>
        <div class="field field-header small-field">Type</div>
        <div class="field field-header small-field">Vendor Name</div>
        <div class="field field-header small-field">Received</div>
        <div class="field field-header small-field">Billed</div>
        <div class="field field-header small-field">Quantity</div>
        <div class="field field-header item_display">Name</div>
        <div class="field field-header small-field">Rate</div>
        <div class="field field-header small-field">Total</div>
        <div class="field field-header small-field">Location</div>
        <div class="clear"></div>
        <?php echo $items_table_html; ?>
    </div>
    <div class="shipping-fields tab-content">
        <div class="field"><b>Ship Date:</b><div><?php echo $fields['shipdate'] ?></div></div>
        <div class="field"><b>Ship Method:</b><div><?php echo $fields['shipmethod'] ?></div></div>
        <div class="field"><b>Tracking #:</b><div><?php echo $fields['linkedtrackingnumbers'] ?></div></div>
        <div class="field"><b>Shipping Address:</b><div><?php echo $fields['shipaddress']; ?></div></div>
        <div class="field"><b>Shipping To:</b><div><?php echo $fields['shipto']; ?></div></div>
        <div class="clear"></div>
    </div>
    <div class="billing-fields tab-content">
        <div class="field"><b>Billing Address:</b><div><?php echo $fields['billaddress']; ?></div></div>
        <div class="field"><b>Terms:</b><div><?php echo $fields['terms'] ?></div></div>
        <div class="field"><b>INCO Term:</b><div><?php echo $fields['incoterm'] ?></div></div>
        <div class="clear"></div>
    </div>
    <div class="relatedrecords-fields tab-content">
        <div class="field field-header small-field">Date</div>
        <div class="field field-header small-field">Type</div>
        <div class="field field-header small-field">Number</div>
        <div class="field field-header small-field">Status</div>
        <div class="field field-header small-field">Amount</div>
        <div class="clear"></div>
        <?php echo $links_table_html; ?>
    </div>
    <div class="messages-fields tab-content">
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Date</div>
        <div class="field field-header">Author</div>
        <div class="field field-header subject">Subject</div>
        <div class="field field-header">Attachment</div>
        <div class="clear"></div>
        <?php echo $messages_table_html; ?>
    </div>
    <div class="notes-fields tab-content">
        <div class="field field-header">Internal ID</div>
        <div class="field field-header">Date</div>
        <div class="field field-header">Author</div>
        <div class="field field-header">Title</div>
        <div class="field field-header note">Note</div>
        <div class="field field-header">Direction</div>
        <div class="clear"></div>
        <?php echo $notes_table_html; ?>
    </div>
    <div class="dynamic-fields tab-content"><?php echo $dynamic_fields; ?></div>
</div>

<script type="text/javascript" src="<?php echo $this->basePath('/js/NStabs.js'); ?>"></script>