<h1><?php echo $title; ?>:</h1>
<?php
    if(isset($this->paginator)) {

        $filterform->prepare();
        echo $this->form()->openTag($filterform);
        echo $this->formRow($filterform->get('recordid'));
        echo $this->formRow($filterform->get('entity'));
        echo $this->formRow($filterform->get('email'));
        echo $this->formRow($filterform->get('phone'));
        echo $this->formRow($filterform->get('trandate'));
        echo $this->formRow($filterform->get('filter'));
        echo '<a href="?" class="buttonlink">Clear</a>';
        echo $this->form()->closeTag();
        ?>
        <div class="container">
            <table class='table'>
                <?php 
                    //echo $table; 

                    $table = $this->paginator->getCurrentItems()->getArrayCopy();

                    if ($table) {
                        foreach($table[0]->data as $col => $data){
                            echo "<th>$col</th>";
                        }
                        unset($table[0]);

                        echo '<tbody>';
                        foreach($table as $row){
                            echo '<tr class="prow">';

                            foreach($row->data as $col => $data){

                                if($col == 'InternalId'){
                                    $url = $this->url('index', array('action' => $subrecord, 'id' => $data));
                                    echo "<td><a href='$url'>$data</a></td>";
                                }else{
                                    if(!preg_match('/tranid|acctnumber/', $col) && is_numeric($data))
                                        $data = number_format($data,2);

                                    echo "<td>$data</td>";
                                }
                            }
                            echo '</tr>';
                        }
                        echo '</tbody>';
                    }
                ?>
                </tbody>
            </table>
        </div>
        <?php
        
        if(isset($query))
            $query = array('query'=> $query);

        echo $this->paginationControl(
            // the paginator object
            $this->paginator,
            // the scrolling style
            'sliding',
            // the partial to use to render the control
            'partial/paginator.phtml',
            // the route to link to when a user clicks a control link
            array('route' => 'netsuite/default',
                  'options' => array('controller' => 'index', 'action' => $action),
                  'query' => $query
                 )
        );
}
?>