<h1>Global Search Results: <?php echo $searchterm; ?></h1>
<?php if(isset($flashMessages))
    echo '<div class="alert alert-warning">'.$flashMessages.'</div>';
?>
<?php if(isset($this->paginator)) { ?>
    <div class="container">
        <table class='table'>
            <tr><?php echo $headers; ?></tr>
            <tbody><?php echo $rows; ?></tbody>
        </table>
    </div>
<?php
    echo $this->paginationControl(
        // the paginator object
        $this->paginator,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        array('route' => 'application/default', 'options' => array('controller' => 'search', 'action' => 'global'), 'query' => array('query'=> array('search-term'=>$searchterm)), 'count'=>$count)
    );
}
?>