<h1>Curl Tester</h1>
<div style="margin-bottom:15px;">
    <form id="curlreq" name="curlreq" action=''; method="post">
        <label>Curl:</label><input type="text" name="curl" style="width:300px;" />
        <input type="submit" name="submit" value="Submit"/><br/>
    </form>
    <br/><br/>
    Param Name: <input id="paramname" type="text" name="paramname" /><button id="addparam">Add Param</button>
</div>
<pre>
    Response:
    <?php echo $body; ?>
</pre>
<script>
    $('#addparam').click(function(){
        var paramname = $('#paramname').val();
        if(paramname.length)
            $('#curlreq').append('<label>'+paramname+': </label><input name="'+paramname+'" type="text" />');
        else
            alert('Post Param must have a name!');
    });
    $('input[name="submit"]').click(function(){$('#loading-box').show();})
</script>
