<?php

$dlm = '?'; // url delimiter
if(isset($query)){
    $dlm = '&';

    // hotfix for SalesOrders
    if(isset($query['query'])){
        if(!empty($query['query'])){
            if(count($query['query'])>1)
                $dlm = '&';
            unset($query['query']['page']);
        }else{
            $dlm = '?';
        }
    }

}else{
    $query = null;
}

if(isset($count) && $count > $this->itemCount)
    $this->totalItemCount += abs($count - $this->itemCount);

if ($this->pageCount):
    ?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,$this->options,$query).$dlm; ?>page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route,$this->options,$query).$dlm;?>page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,$this->options,$query).$dlm; ?>page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
        <div>page <?php echo $this->current; ?> of <?php echo $this->pageCount; ?> (records: <?php echo $this->totalItemCount; ?>)</div>
    </div>
<?php endif; ?>
