<?php 
    /* doesn't work with current index route defined in module.config
    $route = $this->getHelperPluginManager()
                    ->getServiceLocator()
                    ->get('Application')
                    ->getMvcEvent()
                    ->getRouteMatch();
    $appName = 'None';
    if($route)
        $appName = $route->getMatchedRouteName();
    
    $isNetsuite = stripos($appName,'netsuite')!==false;
    */
    $isNetsuite = stripos($this->url(),'netsuite')!==false;
    echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
                        ->prependStylesheet($this->basePath('css/style.css'),'all')
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'),'all')
                        ->prependStylesheet($this->basePath('css/bootstrap.css'),'all') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <?php if($isNetsuite): ?>
                            <img width="32" height="32" src="<?php echo $this->basePath('/img/netsuite-icon.png'); ?>"/>
                        <?php else: ?>
                            <div class="pokeball"></div>
                            <script>
                                var x = 54*( Math.floor(Math.random()*5));
                                var y = 44*( Math.floor(Math.random()*5));
                                $('.pokeball').css('background-position-x',x*-1);
                                $('.pokeball').css('background-position-y',y*-1);
                            </script>
                        <?php endif; ?>
                        &nbsp; <?php echo $this->translate('NS Backup') ?>
                    </a>   
                </div>
                <div class="collapse navbar-collapse">
                    <?php 
                        echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setAddClassToListItem(true)->escapeLabels(true); 
                        if($isNetsuite){
                            //echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav')->setAddClassToListItem(true)->escapeLabels(true)->renderMenu($this->navigation('navigation')->findOneByLabel('Netsuite'));
                            $menuItem = fn($l) => $this->navigation()->menu()->htmlify($this->navigation('navigation')->findOneBy('label', $l));
                            ?>
                            <ul class="nav navbar-nav">
                                <li>
                                    <?php echo $menuItem('Home'); ?>
                                </li>
                                <li>
                                    <?php echo $menuItem('Customers'); ?>
                                </li>
                                <li>
                                    <?php echo $menuItem('Sales Orders'); ?>
                                </li>
                                <li>
                                    <?php echo $menuItem('Cash Sales'); ?>
                                </li>
                                <li>
                                    <?php echo $menuItem('Invoices'); ?>
                                </li>
                            </ul>
                            <?php
                        }
                    ?>
                    <div id="global-search">
                        <form id="gs" name="global-search" method="get" action="/netsuite/search/global">
                            Search <input title="Global Search" name="search-term" value="<?php echo isset($_GET['search-term'])?$_GET['search-term']:''; ?>" placeholder="Global Search" type="search"/>
                            <input type="submit" class="submit" value="Search" />
                        </form>
                    </div>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->navigation()->breadcrumbs(); ?>
            <?php echo $this->content; ?>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <div id="loading-box">
            <div class="spinner">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
        <script>
            $('#global-search .submit, .prow a').click(function(){$('#loading-box').show();});
        </script>
    </body>
</html>
